### ISSUE TITLE
Renew HC Messaging

### ISSUE THREAD

**Issue by agrizzlyadams** [SOZOGlobal/Marketing#2]
vision
mission
values
tagline
manifesto
consumption mantra
commission mantra
the play
narrative

**Comment by Cosmicceph** [comment]
Mission:
Possible: Enable personal wellness; inspire greater awareness. 

Vision:
Possible: Detoxify the planet through a renewed and rewarded community of ecologically-minded entrepreneurs.

Values: 

Tagline: 
Make way for the good. 

Manifesto: (Working on)

Consumption Mantra: 
Remove, renew, restore. (RE3!)
Remove toxins. Renew your body. Restore your health. 

Commission Mantra: 
Get renewed, get rewarded. 
(Possible: "Renew yourself, reward yourself.")

The Play: 
Working on.

Narrative: 
RENEW started with a simple idea: inspire and enable people to make way for the good in their lives, and the lives of others. We envision a less sullied world where people who feel good want to do good while allowing us to reward them. We know that a healthy body deserves a healthy home, which is why we're passionate about helping people renew themselves in tandem with their world. No, we're not stargazing dreamers watching the world through rose-tinted glasses—we're just trying to right what wrongs we can so future generations won't need to make way for the good. Until then, we're harnessing the power of simple goodness and asking people: "What will you Renew?"

—Still in progress, will finish tomorrow—
